plugins {
    id 'net.fabricmc.fabric-loom' version "${loom_version}"
}

version = "${project.mod_version}+mc${project.minecraft_version}"
group = project.maven_group

base {
    archivesName = "axiom-batch-blueprints"
}

loom {
    splitEnvironmentSourceSets()

    mods {
        "axiombatchbp" {
            sourceSet sourceSets.main
            sourceSet sourceSets.client
        }
    }
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    implementation "net.fabricmc:fabric-loader:${project.loader_version}"
    implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"

    compileOnly "org.lwjgl:lwjgl:3.4.1"
    compileOnly "org.lwjgl:lwjgl-nfd:3.4.1"
}

processResources {
    inputs.property "version", project.version
    inputs.property "minecraft_dependency", project.minecraft_dependency

    filesMatching("fabric.mod.json") {
        expand(
            "version": project.version,
            "minecraft_dependency": project.minecraft_dependency
        )
    }
}

tasks.withType(JavaCompile).configureEach {
    it.options.release = 25
}

java {
    sourceCompatibility = JavaVersion.VERSION_25
    targetCompatibility = JavaVersion.VERSION_25
}
